sudo: false
language: python
python:
    - "3.6"
env: 
    - TEST_SUITE='coverage run --source=STC_Path_Testing setup.py test'
    - TEST_SUITE='flake8 --exclude=venv,setup.py'
install: 
    - pip install -r requirements.txt
    - pip install python-coveralls
script: 
    - echo $TEST_SUITE
    - echo $TEST_SUITE > test.sh
    - bash test.sh
after_success: 
    - coverage report
    - coveralls
